Разметка главной страницы
htmlacademy-adaptive/154481-mishka-21 pull request #2
Opened 2020-11-20 18:40 UTC by WhaleisaJoy

2020-11-23 10:06 UTC, craz3r requested changes

2020-11-23 10:06 UTC, craz3r commented on source/index.html
> +            <div>
Это явно структурный блок, ему нужен класс

2020-12-01 19:35 UTC, WhaleisaJoy commented on source/index.html
> +            <div>
Добавлены блоки поиск и корзина

2020-12-03 08:20 UTC, craz3r approved these changes

2020-12-03 08:20 UTC, merged